package io.github.mdasifmustafa.sbx.template.service;

public final class CrudServiceTemplate {

    private CrudServiceTemplate() {}

    public static String serviceInterface(String pkg, String name) {
        return ""
            + "package " + pkg + ";\n\n"
            + "import java.util.List;\n"
            + "import org.springframework.data.domain.Page;\n"
            + "import org.springframework.data.domain.Pageable;\n"
            + "import " + pkg.replace(".service", ".api.dto") + "." + name + "RequestDto;\n"
            + "import " + pkg.replace(".service", ".api.dto") + "." + name + "ResponseDto;\n\n"
            + "public interface " + name + "Service {\n\n"
            + "    " + name + "ResponseDto create(" + name + "RequestDto dto);\n\n"
            + "    " + name + "ResponseDto update(Long id, " + name + "RequestDto dto);\n\n"
            + "    " + name + "ResponseDto getById(Long id);\n\n"
            + "    void delete(Long id);\n\n"
            + "    List<" + name + "ResponseDto> getAll();\n\n"
            + "    Page<" + name + "ResponseDto> getPage(Pageable pageable);\n\n"
            + "}\n";
    }

    public static String serviceImpl(String pkg, String name) {
        String base = pkg.substring(0, pkg.lastIndexOf(".service"));

        return ""
            + "package " + pkg + ";\n\n"
            + "import java.util.List;\n"
            + "import java.util.stream.Collectors;\n"
            + "import jakarta.persistence.EntityNotFoundException;\n"
            + "import org.springframework.data.domain.Page;\n"
            + "import org.springframework.data.domain.Pageable;\n"
            + "import org.springframework.stereotype.Service;\n"
            + "import org.springframework.transaction.annotation.Transactional;\n"
            + "import " + base + ".api.dto." + name + "RequestDto;\n"
            + "import " + base + ".api.dto." + name + "ResponseDto;\n"
            + "import " + base + ".api.mapper." + name + "Mapper;\n"
            + "import " + base + ".domain." + name.toLowerCase() + "." + name + ";\n"
            + "import " + base + ".domain." + name.toLowerCase() + "." + name + "Repository;\n\n"
            + "@Service\n"
            + "@Transactional\n"
            + "public class " + name + "ServiceImpl implements " + name + "Service {\n\n"
            + "    private final " + name + "Repository repository;\n"
            + "    private final " + name + "Mapper mapper;\n\n"
            + "    public " + name + "ServiceImpl(" + name + "Repository repository, " + name + "Mapper mapper) {\n"
            + "        this.repository = repository;\n"
            + "        this.mapper = mapper;\n"
            + "    }\n\n"
            + "    @Override\n"
            + "    public " + name + "ResponseDto create(" + name + "RequestDto dto) {\n"
            + "        " + name + " entity = mapper.toEntity(dto);\n"
            + "        return mapper.toDto(repository.save(entity));\n"
            + "    }\n\n"
            + "    @Override\n"
            + "    public " + name + "ResponseDto update(Long id, " + name + "RequestDto dto) {\n"
            + "        " + name + " entity = repository.findById(id)\n"
            + "            .orElseThrow(() -> new EntityNotFoundException(\"" + name + " not found\"));\n"
            + "        mapper.update(entity, dto);\n"
            + "        return mapper.toDto(repository.save(entity));\n"
            + "    }\n\n"
            + "    @Override\n"
            + "    @Transactional(readOnly = true)\n"
            + "    public " + name + "ResponseDto getById(Long id) {\n"
            + "        return repository.findById(id)\n"
            + "            .map(mapper::toDto)\n"
            + "            .orElseThrow(() -> new EntityNotFoundException(\"" + name + " not found\"));\n"
            + "    }\n\n"
            + "    @Override\n"
            + "    public void delete(Long id) {\n"
            + "        if (!repository.existsById(id)) {\n"
            + "            throw new EntityNotFoundException(\"" + name + " not found\");\n"
            + "        }\n"
            + "        repository.deleteById(id);\n"
            + "    }\n\n"
            + "    @Override\n"
            + "    @Transactional(readOnly = true)\n"
            + "    public List<" + name + "ResponseDto> getAll() {\n"
            + "        return repository.findAll()\n"
            + "            .stream()\n"
            + "            .map(mapper::toDto)\n"
            + "            .collect(Collectors.toList());\n"
            + "    }\n\n"
            + "    @Override\n"
            + "    @Transactional(readOnly = true)\n"
            + "    public Page<" + name + "ResponseDto> getPage(Pageable pageable) {\n"
            + "        return repository.findAll(pageable)\n"
            + "            .map(mapper::toDto);\n"
            + "    }\n\n"
            + "}\n";
    }
}