sbx.name=sbx
sbx.version=0.1.0-SNAPSHOT
sbx.repo.owner=mdasifmustafa
sbx.repo.ownername=Md Asif Mustafa
sbx.repo.name=sbx
sbx.update.channel=stable
# optional, used by AppInfo.getRepoUrl
sbx.repo.url=https://github.com/MdAsifMustafa/sbx.git

